name: release

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: yarn.lock

      - name: Fetch tags
        run: git fetch --tags

      - name: Configure git
        run: git config --global user.email "jakebottrall@gmail.com"

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Release
        run: yarn release
